#!/bin/bash
PATH="/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:${PATH:-}"; export PATH
set -euo pipefail

# gen-reference.sh - regenerate docs/reference.md from the repo itself.
#
#   scripts/gen-reference.sh > docs/reference.md   regenerate
#   scripts/gen-reference.sh --check               non-zero if the file is stale
#
# A hand-maintained inventory of agents, skills, commands and gate checks is
# stale the day after it is written, and nothing notices. So it is derived, and
# --check re-derives it on demand. The scrub gate does not run this; staleness
# is a maintainer's one-command question, not another scan.
#
# Two properties this script owes its caller:
#   - DETERMINISTIC. Same repo state in, byte-identical bytes out. No
#     timestamps, no hostname, no absolute paths, LC_ALL=C so glob and sort
#     order do not depend on the machine's locale.
#   - LOUD ON EMPTY. Every section dies rather than emitting an empty table. A
#     generator that silently drops a section turns check 13 into a check that
#     compares nothing to nothing, which is the failure mode the whole gate
#     exists to refuse.
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DOC="docs/reference.md"

die() { printf 'gen-reference: %s\n' "$1" >&2; exit 1; }

case "${1:-}" in
  ''|--check) ;;
  *) die "usage: gen-reference.sh [--check]" ;;
esac

# One frontmatter value, or empty when the key is absent. Stops at the closing
# delimiter so a horizontal rule in the body cannot be read as a field.
# Pipes are escaped because every value below lands in a Markdown table cell.
# ponytail: single-line scalars only. A folded value (`description: >`) renders
# as a lone ">" here - visible in the table rather than silently truncated.
# Nothing in this repo uses one; parse YAML properly if that changes.
fm() {
  awk -v k="$2" '
    /^---[[:space:]]*$/ { n++; next }
    n == 1 && $0 ~ "^" k ":" { sub("^" k ":[[:space:]]*", ""); gsub(/\|/, "\\|"); print; exit }
  ' "$1"
}

# file:line for a config key, resolved now rather than hardcoded. A citation
# nobody re-derives is a citation that rots; this one fails the build instead.
cite() {
  local n
  n=$(grep -nF -m1 -e "$1" "$2" | cut -d: -f1) || true
  [ -n "$n" ] || die "cannot find '$1' in $2 - the config table would cite a line that is not there"
  printf '`%s:%s`' "$2" "$n"
}

# Every banned glyph, plus the arrows, transliterated on the way out. Several
# agent and skill descriptions in this repo contain em dashes and arrows, and
# docs/reference.md is client-facing, so check 8 rejects them. This is the
# safety net required of any generator that writes a client-facing file, not a
# licence to write tells into the frontmatter.
normalize() {
  perl -CSD -pe '
    s/[\x{2014}\x{2013}\x{2012}\x{2015}\x{00B7}]/-/g;
    s/[\x{2018}\x{2019}]/\x27/g;
    s/[\x{201C}\x{201D}]/"/g;
    s/\x{2026}/.../g;
    s/\x{00A0}/ /g;
    s/\x{200B}//g;
    s/\x{00D7}/x/g;
    s/\x{2192}/->/g;
    s/\x{2190}/<-/g;
    s/&(?:mdash|ndash|#8212|#8211|#x201[45]|middot|#183|#xB7);/-/gi;
    s/&(?:hellip|#8230|#x2026);/.../gi;
    s/&(?:nbsp|#160|#xA0);/ /gi;
    s/&(?:times|#215|#xD7);/x/gi;
  '
}

render() {
  cat <<'HEADER'
# Reference

Every table below is derived from the repo. Do not edit this file by hand. After changing an agent,
a skill, a command, a module, a config key, or a gate check, regenerate it:

```bash
scripts/gen-reference.sh > docs/reference.md
```

To find out whether it has gone stale without rewriting it, ask. The exit status is non-zero when
the committed file no longer matches the repo, and the diff says which table moved:

```bash
scripts/gen-reference.sh --check
```

## Agents

Definitions live in `agents/`. The tier token is resolved to a real model by `harness install`,
using the binding in `config/models.conf`.

| Agent | Tier | Effort | Tools | What it is for |
|---|---|---|---|---|
HEADER
  local f n rows=0
  for f in agents/*.md; do
    [ -e "$f" ] || continue
    n=$(fm "$f" name); [ -n "$n" ] || die "$f has no name: in its frontmatter"
    printf '| `%s` | `%s` | %s | %s | %s |\n' \
      "$n" "$(fm "$f" model)" "$(fm "$f" effort | grep . || echo '-')" \
      "$(fm "$f" tools | grep . || echo '-')" "$(fm "$f" description)"
    rows=$((rows+1))
  done
  [ "$rows" -gt 0 ] || die "no agent definitions found - an empty agents table is not the same as no agents"

  cat <<'HEADER'

## Skills

Each skill is a directory under `skills/` holding a `SKILL.md`. The directory name is the invocable
token; the `name:` field is the display name, and the two differ for the vendored skills.

| Skill | Directory | What it is for | When to use it |
|---|---|---|---|
HEADER
  rows=0
  for f in skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    n=$(fm "$f" name); [ -n "$n" ] || die "$f has no name: in its frontmatter"
    local dir="${f#skills/}"; dir="${dir%/SKILL.md}"
    printf '| %s | `%s` | %s | %s |\n' \
      "$n" "$dir" "$(fm "$f" description)" "$(fm "$f" when_to_use | grep . || echo '-')"
    rows=$((rows+1))
  done
  [ "$rows" -gt 0 ] || die "no SKILL.md files found - an empty skills table is not the same as no skills"

  cat <<'HEADER'

## Slash commands

Files in `commands/`. The filename is the command.

| Command | What it does |
|---|---|
HEADER
  rows=0
  for f in commands/*.md; do
    [ -e "$f" ] || continue
    local cmd="${f#commands/}"; cmd="${cmd%.md}"
    printf '| `/%s` | %s |\n' "$cmd" "$(fm "$f" description | grep . || echo '-')"
    rows=$((rows+1))
  done
  [ "$rows" -gt 0 ] || die "no command files found - an empty commands table is not the same as no commands"

  # Fixed tables: these mirror cmd_add and cmd_add_tool in bin/harness. They are
  # not derived, because deriving them would mean parsing a bash case statement
  # to learn less than reading it. Change bin/harness, change these.
  cat <<'HEADER'

## Modules

`harness add <module>` writes one module into the current repo. Paths are relative to the repo root.

| Module | Writes |
|---|---|
| `workspace-brain` | `.claude/CLAUDE.md`, `.claude/rules/workflow.md`, `knowledge/` |
| `context` | `.claude/context/` |
| `multi-agent` | `.claude/rules/multi-agent-runtime.md` |
| `phase` | `phases/`, from `templates/phase/` |
| `project-state` | `.project-state/` |

`harness add --tool <name>` writes the pointer file another coding tool reads, so it gets the same
core instructions.

| Tool | Writes |
|---|---|
| `auggie` | `~/.augment/rules/harness-core.md`, a copy of `AGENTS.md` |
| `codex` | `~/.codex/AGENTS.md`, a copy of `AGENTS.md` |
| `cursor` | `.cursor/rules/harness-core.mdc`, a copy of `AGENTS.md` |
| `gemini` | `GEMINI.md`, a one-line import of `AGENTS.md` |
| `intent` | nothing. Prints how Intent picks up `AGENTS.md` and `skills/` on its own |
| `cosmos` | nothing. Prints the two configuration paths and what this harness does not generate |

## Configuration keys

HEADER
  printf '| Key | Where | What it does |\n|---|---|---|\n'
  printf '| `includeCoAuthoredBy` | %s | `false`. Suppresses the AI co-author trailer on every commit. |\n' \
    "$(cite '"includeCoAuthoredBy"' config/settings.portable.json)"
  printf '| `CLAUDE_AUTOCOMPACT_PCT_OVERRIDE` | %s | `"85"`. Starts auto-compaction at 85 percent of the context window. |\n' \
    "$(cite 'CLAUDE_AUTOCOMPACT_PCT_OVERRIDE' config/settings.portable.json)"
  printf '| `Agent\\|Task` matcher | %s | The `PreToolUse` matcher that routes every subagent spawn through `hooks/require-agent-model.sh`. |\n' \
    "$(cite '"Agent|Task"' config/settings.portable.json)"
  printf '| `CLAUDE_CONFIG_DIR` | %s | Environment variable. Overrides the install target, which otherwise defaults to `.claude` under your home directory. |\n' \
    "$(cite 'CLAUDE_CONFIG_DIR' bin/harness)"
  printf '| `--user` | %s | Accepted and ignored. `harness install` is user-scope already; the flag reads as documentation at the call site. |\n' \
    "$(cite '--user)' bin/harness)"

  cat <<'HEADER'

## Scrub gate

`verify.sh` runs these, counts them, and refuses to report success unless the number that ran
matches the number it expected.

| # | Check |
|---|---|
HEADER
  # The numbered comment lines in verify.sh ARE the checks. The `# ---- SECTION`
  # lines are a different shape (no number) and must not be picked up here.
  local checks
  checks=$(grep -E '^# [0-9]+ -+ ' verify.sh | sed -E 's/^# ([0-9]+) -+ +(.*)$/| \1 | \2 |/')
  [ -n "$checks" ] || die "no numbered check comments in verify.sh - an empty gate table is not the same as no gate"
  printf '%s\n' "$checks"
}

out=$(render | normalize)

# Verify the OUTPUT, not the source. If a glyph is ever added to check 8's class
# without a mapping above, this fails here rather than in a red gate run.
printf '%s\n' "$out" \
  | perl -CSD -ne 'exit 1 if /[\x{2014}\x{2013}\x{2012}\x{2015}\x{2018}\x{2019}\x{201C}\x{201D}\x{2026}\x{00A0}\x{200B}\x{00D7}\x{00B7}]/' \
  || die "a banned glyph survived normalize() - add it to the map above"

if [ "${1:-}" = "--check" ]; then
  [ -r "$DOC" ] || die "$DOC is missing - regenerate it with: scripts/gen-reference.sh > $DOC"
  printf '%s\n' "$out" | diff -u "$DOC" - \
    || die "$DOC is stale - regenerate it with: scripts/gen-reference.sh > $DOC"
  printf '%s is current\n' "$DOC"
  exit 0
fi

printf '%s\n' "$out"
