#!/bin/bash
PATH="/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:${PATH:-}"; export PATH
set -uo pipefail

# The PATH line above re-runs in EVERY child of this script, re-prepending the
# system directories ahead of whatever a caller put in front of them. That is
# fine in production and fatal under test: the selftest's stub CLI lives in a
# temp dir, so on a machine where the real one IS installed in a system dir the
# stub LOSES and the selftest silently runs against the live vendor instead of
# the fixture. This hook is the one thing that gets in front of that line.
# Nothing but the selftests ever set it, and the selftests assert the stub
# actually ran rather than trusting that it did.
[ -z "${HARNESS_PATH_PREPEND:-}" ] || PATH="$HARNESS_PATH_PREPEND:$PATH"

# resolve-tier.sh - bind a harness TIER (or the external REVIEWER) to a literal
# model id by ASKING THE VENDOR, instead of typing one by hand.
#
# The harness rule is unchanged: prose names a TIER, only a config file binds a
# tier to a literal (AGENTS.md, "Naming tiers versus naming models"). On Augment
# the allowlist is per-company and moves without telling us, so the binding is
# DISCOVERED. `config/models.conf` (the Claude Code side) stays hand-written.
#
# usage:
#   scripts/resolve-tier.sh <TIER_FRONTIER_THINK|TIER_FRONTIER_DO|TIER_MID|TIER_SMALL|REVIEWER>
#   scripts/resolve-tier.sh [<role>] --write-conf [--force]
#   scripts/resolve-tier.sh --selftest
#
# stdout is the bare id and nothing else, so a caller can write
#   --model "$(scripts/resolve-tier.sh REVIEWER)"
# stderr carries one audit line: what was resolved, from where, by which chain
# of predicates, and how many models were excluded.
#
# exit: 0 resolved | 2 usage | 3 UNAVAILABLE (no eligible model) | 4 schema
#
# WHICH SURFACES RESOLVE LIVE, AND WHICH AT GENERATION TIME
#   LIVE, re-resolved on every invocation:
#     scripts/external-review.sh, any `auggie --print` the harness or the
#     runbook drives, and a render step that shells out per run.
#   GENERATION TIME, written into a file once and re-bound only when the
#   runbook's re-bind step runs (a subagent's `model:` is a static frontmatter
#   field, aug_cli_subagents.md:66):
#     .augment/agents/*.md, plugins/, resolved commands/, and
#     config/models.auggie.conf itself.
#   NOT RESOLVABLE by this harness at all:
#     a Cosmos Expert bundle's model field (set at `apply`), and the Claude Code
#     side, where config/models.conf is hand-written.
#   ponytail: no drift check against the live list. Re-bind on the runbook's
#   named triggers; nothing here notices the vendor list changing underneath a
#   generated file.
#
# WHAT ACTUALLY EXECUTES ON A MACHINE WITHOUT AUGGIE
#   Discovery needs `auggie` on PATH. On a machine without it the ONLY way the
#   discovery path runs is --selftest, which puts a stub `auggie` on PATH from a
#   temp dir. Likewise the `source=conf` branch: config/models.auggie.conf is
#   generated by the runbook and is NOT in this repo, so that branch is
#   exercised only by the selftest writing one into a temp dir and pointing
#   HARNESS_AUGGIE_CONF at it.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SELF="$ROOT/scripts/${BASH_SOURCE[0]##*/}"

# Both confs are overridable so the selftest can point at a temp dir. Nothing
# else sets them; the defaults are the real paths.
REVIEWER_CONF="${HARNESS_REVIEWER_CONF:-$ROOT/config/reviewer.conf}"
AUGGIE_CONF="${HARNESS_AUGGIE_CONF:-$ROOT/config/models.auggie.conf}"

# ---------------------------------------------------------------- SCHEMA KNOBS
#
# The shape of `auggie models list --full-info` is NOT FOUND in the docs
# snapshot: aug_cli_reference.md:122 names the FIELDS it carries (display names,
# descriptions, cost tiers, effort levels, the account default) but not their
# JSON keys. These five expressions are that schema, and they are the one thing
# the runbook (step 5a) edits on the work machine after looking at one real
# entry. Guessing wrong is loud, not silent: any entry missing one of the four
# required fields exits 4 and prints the raw entry.
#
# The account default field is deliberately absent. It is never read. On this
# vendor it is a Claude model, and falling back to it would hand the external
# review gate a same-family reviewer with nobody noticing.
MODELS_JQ='if type=="array" then . else (.models // .data // []) end'
F_ID='.id'
F_NAME='.displayName'
F_COST='.costTier'
F_EFFORT='.effortLevels'

# Cost tier is the vendor's own capability signal, so it is the primary sort
# key. Numeric values are read as-is, HIGHER MEANING MORE CAPABLE. If the values
# are not integers - or if this vendor numbers them the other way round - set
# COST_TIER_ORDER to the tier labels highest-first and it wins outright.
# Runbook step 5a. Example: COST_TIER_ORDER="premium standard economy"
COST_TIER_ORDER="${COST_TIER_ORDER:-}"

# From section 3.1 of the plan: the primary reviewer pin, then the fallback,
# matched case-insensitively as whole words against the display name. This is
# the ONLY family preference in the script. The four work tiers are ranked
# capability-first and may bind an anthropic model if it ranks highest - a tier
# is defined by the task (AGENTS.md "Model tiers"), not by the vendor. Only the
# reviewer carries a family predicate, because a second opinion is worth having
# only when it comes from a different blind spot.
REVIEWER_PREF="${REVIEWER_PREF:-astra sol}"

die()  { printf 'resolve-tier: %s\n' "$1" >&2; exit "${2:-2}"; }
note() { printf 'resolve-tier: %s\n' "$1" >&2; }

# ---------------------------------------------------------------- conf reading
#
# Same two-line normalisation `load_models` uses in bin/harness: strip from the
# first `#` onward, then strip all whitespace. A trailing comment on a value is
# therefore free, which is how --write-conf records WHY each tier bound.
conf_get() { # conf_get <file> <key>
  [ -f "$1" ] || return 1
  local k v
  while IFS='=' read -r k v; do
    k="${k%%#*}"; k="$(printf '%s' "$k" | tr -d '[:space:]')"
    [ -n "$k" ] || continue
    v="${v%%#*}"; v="$(printf '%s' "$v" | tr -d '[:space:]')"
    [ "$k" = "$2" ] || continue
    printf '%s\n' "$v"
    return 0
  done < "$1"
  return 1
}

# ---------------------------------------------------------------- the model set
# Parallel arrays, one entry per model, in the vendor's own list order. That
# order is the tiebreak below, so it has to survive the pipeline intact.
M_ID=(); M_NAME=(); M_COST=(); M_EFFORT=(); M_FAMILY=(); M_RANK=(); M_SPEED=(); M_EFFORT_OK=()

# A word-boundary test that does not use \b. macOS libc regcomp has no \b, the
# same liveness trap verify.sh:181 documents for git grep: a pattern that
# matches NOTHING turns a classifier into a permanent "no". Everything here is
# spelled with explicit boundaries and the selftest proves each branch fires.
BOUND_L='(^|[^a-z0-9])'
BOUND_R='([^a-z0-9]|$)'

family_of() { # family_of <lowercased "id name">
  local h="$1"
  # ROUTER FIRST, and this order is load-bearing. "Prism (Claude + GPT)" carries
  # both an anthropic and an openai token in its display name; tested after
  # either one it would classify as that family and escape the router predicate.
  if   [[ "$h" =~ ${BOUND_L}prism${BOUND_R} ]]; then printf 'router\n'
  elif [[ "$h" =~ (claude|sonnet|opus|haiku) ]];  then printf 'anthropic\n'
  elif [[ "$h" =~ (gpt|${BOUND_L}o[0-9]) ]];      then printf 'openai\n'
  elif [[ "$h" =~ grok ]];                        then printf 'xai\n'
  elif [[ "$h" =~ gemini ]];                      then printf 'google\n'
  elif [[ "$h" =~ kimi ]];                        then printf 'moonshot\n'
  elif [[ "$h" =~ glm ]];                         then printf 'zhipu\n'
  elif [[ "$h" =~ deepseek ]];                    then printf 'deepseek\n'
  else printf 'unknown\n'; fi
}

# The fast tier of a family. Bounded, because `mini` is a substring of `gemini`:
# unbounded, this predicate quietly excludes every Google model, not just Flash.
is_speed() { [[ "$1" =~ ${BOUND_L}(flash|mini|nano|lite|fast)${BOUND_R} ]]; }

rank_of() { # rank_of <raw cost tier> -> integer, larger = more capable
  local c="$1" i=0 n
  if [ -n "$COST_TIER_ORDER" ]; then
    set -- $COST_TIER_ORDER
    n=$#
    for t in "$@"; do
      i=$((i+1))
      [ "$t" = "$c" ] && { printf '%d\n' $((n - i + 1)); return 0; }
    done
    return 1
  fi
  [[ "$c" =~ ^[0-9]+$ ]] || return 1
  printf '%d\n' "$c"
}

load_models_list() {
  local raw rc filter line idx id name cost effort
  command -v auggie >/dev/null 2>&1 \
    || die "auggie is not on PATH - cannot discover the model list. UNAVAILABLE." 3
  raw="$(auggie models list --full-info 2>&1)"; rc=$?
  [ $rc -eq 0 ] || { printf '%s\n' "$raw" >&2; die "auggie models list --full-info exited $rc. UNAVAILABLE." 3; }

  filter=$(printf '%s | to_entries[] | [ (.key|tostring), ((.value|%s)//""|tostring), ((.value|%s)//""|tostring), ((.value|%s)//""|tostring), ((.value|%s) as $e | if $e==null then "" elif ($e|type)=="array" then ($e|map(tostring)|join(",")) else ($e|tostring) end) ] | @tsv' \
    "$MODELS_JQ" "$F_ID" "$F_NAME" "$F_COST" "$F_EFFORT")

  local tsv
  tsv="$(printf '%s' "$raw" | jq -r "$filter" 2>/dev/null)" \
    || die "could not parse auggie models list --full-info as JSON - unrecognised model-list shape. Fix MODELS_JQ (runbook step 5a)." 4
  [ -n "$tsv" ] || die "auggie models list --full-info yielded no entries - unrecognised model-list shape. Fix MODELS_JQ (runbook step 5a)." 4

  while IFS=$'\t' read -r idx id name cost effort; do
    # EVERY entry must carry all four fields. A null here means a knob above is
    # wrong, and a wrong knob that merely skipped the entry would silently
    # shrink the candidate set - the shape of failure this whole gate exists to
    # refuse. Report the raw entry so the runbook can read the real keys off it.
    if [ -z "$id" ] || [ -z "$name" ] || [ -z "$cost" ] || [ -z "$effort" ]; then
      printf 'resolve-tier: first raw entry:\n' >&2
      printf '%s' "$raw" | jq -r "($MODELS_JQ) | .[0]" >&2 2>/dev/null
      die "entry $idx (id='$id') is missing one of id/displayName/costTier/effortLevels - unrecognised model-list shape. Fix the schema knobs (runbook step 5a)." 4
    fi
    local rank haystack
    rank="$(rank_of "$cost")" || die "cost tier '$cost' on '$id' is not an integer and is not in COST_TIER_ORDER. Set COST_TIER_ORDER at the top of this script, highest first (runbook step 5a)." 4
    haystack="$(printf '%s %s' "$id" "$name" | tr '[:upper:]' '[:lower:]')"
    M_ID+=("$id"); M_NAME+=("$name"); M_COST+=("$cost"); M_EFFORT+=("$effort")
    M_RANK+=("$rank")
    M_FAMILY+=("$(family_of "$haystack")")
    if is_speed "$haystack"; then M_SPEED+=(1); else M_SPEED+=(0); fi
    # FRONTIER_* and REVIEWER run at high or max effort: the reviewer is the
    # last gate before a wave merges, and a frontier tier that cannot be asked
    # to think hard is not a frontier tier.
    if [[ ",$effort," =~ ,(high|max), ]]; then M_EFFORT_OK+=(1); else M_EFFORT_OK+=(0); fi
  done <<< "$tsv"
}

# ---------------------------------------------------------------- selection
#
# Sets SEL_ID / SEL_RULE / SEL_EXCLUDED, or exits 3 listing every model with the
# predicate that excluded it. It NEVER falls through to a default.
SEL_ID=""; SEL_RULE=""; SEL_EXCLUDED=0; SEL_NOTE=""

exclusion_for() { # exclusion_for <index> <role> -> reason, empty if eligible
  local i="$1" role="$2"
  # A router blend is excluded for every role, not just the reviewer: it can
  # carry the builder's own family (so it partly shares its blind spots), and
  # which model actually answered is not auditable afterwards.
  [ "${M_FAMILY[$i]}" = "router" ] && { printf 'router blend (carries an undisclosed family; its pick is not auditable)\n'; return; }
  # The fast tier of a family is the wrong instrument for a correctness gate.
  # SMALL is exactly the role it IS right for, so SMALL allows it.
  if [ "${M_SPEED[$i]}" = "1" ] && [ "$role" != "TIER_SMALL" ]; then
    printf 'speed tier (the fast variant of its family; allowed for TIER_SMALL only)\n'; return
  fi
  case "$role" in
    TIER_FRONTIER_THINK|TIER_FRONTIER_DO|REVIEWER)
      [ "${M_EFFORT_OK[$i]}" = "1" ] || { printf 'effort levels (%s) include neither high nor max\n' "${M_EFFORT[$i]}"; return; } ;;
  esac
  # The ONLY family predicate in the script, and only for the reviewer.
  if [ "$role" = "REVIEWER" ] && [ "${M_FAMILY[$i]}" = "anthropic" ]; then
    printf 'same family as the author (anthropic) - a same-family review gate is vacuous\n'; return
  fi
  printf ''
}

unavailable() { # unavailable <role> - list everything and why, then exit 3
  local role="$1" i r
  printf 'resolve-tier: UNAVAILABLE - no eligible model for %s. Every model seen:\n' "$role" >&2
  for i in "${!M_ID[@]}"; do
    r="$(exclusion_for "$i" "$role")"
    [ -n "$r" ] || r="eligible, but outranked on cost tier"
    printf '  - %s [%s] "%s" cost=%s effort=%s: %s\n' \
      "${M_ID[$i]}" "${M_FAMILY[$i]}" "${M_NAME[$i]}" "${M_COST[$i]}" "${M_EFFORT[$i]}" "$r" >&2
  done
  printf 'resolve-tier: the account default model is never read; an empty result fails loudly instead.\n' >&2
  exit 3
}

# best_at <role> <mode:max|min> [strictly-below-rank] -> echoes "<idx> <rank>"
# Iterates in vendor list order and compares STRICTLY, so the first model at the
# winning rank wins. That is the tiebreak, and it is deterministic.
best_at() {
  local role="$1" mode="$2" below="${3:-}" i best="" bestrank=""
  for i in "${!M_ID[@]}"; do
    [ -z "$(exclusion_for "$i" "$role")" ] || continue
    [ -z "$below" ] || [ "${M_RANK[$i]}" -lt "$below" ] || continue
    if [ -z "$best" ]; then best="$i"; bestrank="${M_RANK[$i]}"; continue; fi
    if [ "$mode" = "max" ]; then
      [ "${M_RANK[$i]}" -gt "$bestrank" ] && { best="$i"; bestrank="${M_RANK[$i]}"; }
    else
      [ "${M_RANK[$i]}" -lt "$bestrank" ] && { best="$i"; bestrank="${M_RANK[$i]}"; }
    fi
  done
  [ -n "$best" ] || return 1
  printf '%s %s\n' "$best" "$bestrank"
}

count_excluded() { # count_excluded <role>
  local role="$1" i n=0
  for i in "${!M_ID[@]}"; do [ -z "$(exclusion_for "$i" "$role")" ] || n=$((n+1)); done
  printf '%d\n' "$n"
}

select_role() {
  local role="$1" pick idx rank frontier frank i
  SEL_ID=""; SEL_RULE=""; SEL_NOTE=""
  SEL_EXCLUDED="$(count_excluded "$role")"

  case "$role" in
    REVIEWER)
      # The preference list wins over cost tier when it matches, because section
      # 3.1 picked these two on evidence from this codebase, not on a spec sheet.
      for p in $REVIEWER_PREF; do
        for i in "${!M_ID[@]}"; do
          [ -z "$(exclusion_for "$i" "$role")" ] || continue
          local h; h="$(printf '%s %s' "${M_ID[$i]}" "${M_NAME[$i]}" | tr '[:upper:]' '[:lower:]')"
          local lp; lp="$(printf '%s' "$p" | tr '[:upper:]' '[:lower:]')"
          if [[ "$h" =~ ${BOUND_L}${lp}${BOUND_R} ]]; then
            SEL_ID="${M_ID[$i]}"
            SEL_RULE="not-router,not-speed-tier,effort>=high,non-anthropic,preference=$p"
            return 0
          fi
        done
      done
      pick="$(best_at "$role" max)" || unavailable "$role"
      idx="${pick% *}"
      SEL_ID="${M_ID[$idx]}"
      SEL_RULE="not-router,not-speed-tier,effort>=high,non-anthropic,highest-cost-tier (no preference matched)"
      ;;
    TIER_FRONTIER_THINK|TIER_FRONTIER_DO)
      pick="$(best_at "$role" max)" || unavailable "$role"
      idx="${pick% *}"
      SEL_ID="${M_ID[$idx]}"
      SEL_RULE="not-router,not-speed-tier,effort>=high,highest-cost-tier"
      ;;
    TIER_MID)
      # MID is defined relative to FRONTIER: the next distinct cost tier below
      # it. With no frontier candidate there is no anchor, and computing against
      # an undefined one would silently return the top of the whole list.
      frontier="$(best_at TIER_FRONTIER_DO max)" || unavailable TIER_FRONTIER_DO
      frank="${frontier#* }"
      if pick="$(best_at "$role" max "$frank")"; then
        idx="${pick% *}"
        SEL_RULE="not-router,not-speed-tier,highest-cost-tier below FRONTIER's ($frank)"
      else
        pick="$(best_at "$role" max)" || unavailable "$role"
        idx="${pick% *}"
        SEL_RULE="not-router,not-speed-tier,FRONTIER's own cost tier ($frank)"
        SEL_NOTE="only one eligible cost tier exists, so MID binds the same one as FRONTIER"
      fi
      SEL_ID="${M_ID[$idx]}"
      ;;
    TIER_SMALL)
      pick="$(best_at "$role" min)" || unavailable "$role"
      idx="${pick% *}"
      SEL_ID="${M_ID[$idx]}"
      SEL_RULE="not-router,speed-tier-allowed,lowest-cost-tier"
      ;;
    *) die "unknown role: $role" ;;
  esac
}

resolve() { # resolve <role> -> sets SEL_ID/SEL_SOURCE/SEL_RULE
  local role="$1" pinned
  SEL_SOURCE=""
  # PIN BEATS DISCOVERY, always. Discovery fills a blank; it never overrides an
  # explicit value someone wrote down.
  if [ "$role" = "REVIEWER" ]; then
    pinned="${REVIEWER_MODEL:-}"
    [ -n "$pinned" ] || pinned="$(conf_get "$REVIEWER_CONF" REVIEWER_MODEL || true)"
    if [ -n "$pinned" ]; then
      SEL_ID="$pinned"; SEL_SOURCE="pinned"; SEL_RULE="explicit pin, returned untouched"; SEL_EXCLUDED=0; SEL_NOTE=""
      return 0
    fi
  else
    pinned="$(conf_get "$AUGGIE_CONF" "$role" || true)"
    if [ -n "$pinned" ]; then
      SEL_ID="$pinned"; SEL_SOURCE="conf"; SEL_RULE="bound in ${AUGGIE_CONF##*/}"; SEL_EXCLUDED=0; SEL_NOTE=""
      return 0
    fi
  fi
  [ "${#M_ID[@]}" -gt 0 ] || load_models_list
  select_role "$role"
  SEL_SOURCE="discovered"
}

report() { # report <role>
  printf 'resolve-tier: resolved %s -> %s (source=%s; rule=%s; excluded=%s)\n' \
    "$1" "$SEL_ID" "$SEL_SOURCE" "$SEL_RULE" "$SEL_EXCLUDED" >&2
  [ -z "$SEL_NOTE" ] || note "$SEL_NOTE"
}

write_conf() { # write_conf <force>
  local force="$1" tmp role
  # put()'s rule from bin/harness: an existing file IS the pin, and --force is
  # the only way past it.
  if [ -e "$AUGGIE_CONF" ] && [ "$force" != "1" ]; then
    die "$AUGGIE_CONF exists; re-run with --force to re-discover (an existing conf is a pin)"
  fi
  # Resolve all four BEFORE writing anything. A partial conf that bound two
  # tiers and dropped two would be read by load_models as a hard failure at
  # best and a wrong binding at worst, so an exit 3 on any tier writes nothing.
  local ids=() rules=()
  for role in TIER_FRONTIER_THINK TIER_FRONTIER_DO TIER_MID TIER_SMALL; do
    resolve "$role"; report "$role"
    ids+=("$SEL_ID"); rules+=("$SEL_RULE")
  done
  tmp="$(mktemp)" || die "mktemp failed"
  {
    printf '# generated by scripts/resolve-tier.sh --write-conf on %s; re-run with --force to re-discover\n' "$(date +%Y-%m-%d)"
    printf '# Tier -> model binding for the Augment CLI, DISCOVERED from the vendor\n'
    printf '# allowlist rather than typed. Tier meanings live in AGENTS.md; this file\n'
    printf '# only binds them to literals. The trailing comment on each line is the\n'
    printf '# predicate chain that chose it.\n\n'
    local i=0
    for role in TIER_FRONTIER_THINK TIER_FRONTIER_DO TIER_MID TIER_SMALL; do
      printf '%s=%s  # %s\n' "$role" "${ids[$i]}" "${rules[$i]}"
      i=$((i+1))
    done
  } > "$tmp" || die "could not write $tmp"
  mkdir -p "$(dirname "$AUGGIE_CONF")" || die "could not create $(dirname "$AUGGIE_CONF")"
  mv "$tmp" "$AUGGIE_CONF" || die "could not move $tmp to $AUGGIE_CONF"
  note "wrote $AUGGIE_CONF"
}

# ---------------------------------------------------------------- selftest
#
# A stub `auggie` on PATH is the only way the discovery path executes on a
# machine without the vendor CLI. Each fixture is a full --full-info payload.
SELFTEST_TMP=""
selftest_cleanup() { [ -z "$SELFTEST_TMP" ] || rm -rf "$SELFTEST_TMP"; }
selftest() {
  local tmp T=0 F=0
  tmp="$(mktemp -d)" || die "mktemp -d failed"
  # The trap runs after selftest's locals are gone, so the path it removes has
  # to be a global. A `local tmp` here left the temp dir on disk and printed an
  # unbound-variable error AFTER the OK line.
  SELFTEST_TMP="$tmp"
  trap selftest_cleanup EXIT
  # This machine exports REVIEWER_CLI/REVIEWER_MODEL for the real reviewer. Left
  # set, every assertion below would come back source=pinned and the whole
  # discovery path would go untested while printing green.
  unset REVIEWER_MODEL HARNESS_AUGGIE_CONF HARNESS_REVIEWER_CONF COST_TIER_ORDER REVIEWER_PREF
  mkdir -p "$tmp/bin"
  cat > "$tmp/bin/auggie" <<'STUB'
#!/bin/bash
: > "$STUB_MARK"
[ "$*" = "models list --full-info" ] || { printf 'stub auggie: unexpected args: %s\n' "$*" >&2; exit 64; }
cat "$AUGGIE_FIXTURE"
STUB
  chmod +x "$tmp/bin/auggie"
  export STUB_MARK="$tmp/stub-ran"
  export HARNESS_PATH_PREPEND="$tmp/bin"
  PATH="$tmp/bin:$PATH"; export PATH
  : > "$tmp/reviewer.conf"
  export HARNESS_REVIEWER_CONF="$tmp/reviewer.conf"
  export HARNESS_AUGGIE_CONF="$tmp/models.auggie.conf"

  ok() { T=$((T+1)); printf '  ok   %s\n' "$1"; }
  no() { T=$((T+1)); F=$((F+1)); printf '  FAIL %s\n' "$1"; }
  is() { if [ "$2" = "$3" ]; then ok "$1"; else no "$1 -- expected '$2', got '$3'"; fi; }
  has() { case "$3" in *"$2"*) ok "$1" ;; *) no "$1 -- '$2' not found in: $3" ;; esac; }

  # run <fixture> <args...> -> stdout in $OUT, stderr in $ERR, status in $RC
  run() {
    local fx="$1"; shift
    AUGGIE_FIXTURE="$tmp/$fx.json" OUT="" ERR="" RC=0
    export AUGGIE_FIXTURE="$tmp/$fx.json"
    OUT="$("$SELF" "$@" 2>"$tmp/stderr")"; RC=$?
    ERR="$(cat "$tmp/stderr")"
  }

  # -- fixture: the thirteen allowlist entries from plan section 3.1, plus four
  # negative entries. Each negative exists because without it an assertion below
  # passes for an INCIDENTAL reason, which a mutation run proved:
  #   "Gemini 3.8 Pro"  - `mini` is a substring of `gemini`. Unbounded, the
  #                       speed-tier predicate excludes every Google model.
  #   "OpenAI o4 ..."   - the o-series branch of the openai regex, which is
  #                       otherwise never exercised by any id on the list.
  #   "Grok 4.6 Fast"   - a speed tier at a HIGH cost tier. Every real Flash sits
  #                       at the bottom, so deleting the speed predicate changed
  #                       no outcome and the "never a speed tier" assertions
  #                       stayed green over a gutted check.
  #   "Prism (Economy)" - a router at the LOWEST cost tier, so deleting the
  #                       router predicate changes what TIER_SMALL binds.
  # The two real routers sit at the TOP cost tier for the same reason: at cost 6
  # they tied with Claude Opus 5 and lost the tiebreak, so dropping `prism` from
  # the router regex left every assertion green.
  # Claude Opus 5 outranks every non-router on purpose: the four WORK tiers are
  # capability-first and may bind an anthropic model, while REVIEWER may not.
  cat > "$tmp/full.json" <<'JSON'
{"models":[
 {"id":"gpt-6-astra","displayName":"GPT-6 Astra","costTier":5,"effortLevels":["low","medium","high","max"]},
 {"id":"gpt-5.6-sol","displayName":"GPT-5.6 Sol","costTier":4,"effortLevels":["low","medium","high"]},
 {"id":"gpt-5.6-terra","displayName":"GPT-5.6 Terra","costTier":4,"effortLevels":["low","medium","high"]},
 {"id":"gpt-5.6-luna","displayName":"GPT-5.6 Luna","costTier":3,"effortLevels":["low","medium"]},
 {"id":"claude-opus-5","displayName":"Claude Opus 5","costTier":6,"effortLevels":["low","medium","high","max"]},
 {"id":"claude-sonnet-5","displayName":"Claude Sonnet 5","costTier":4,"effortLevels":["low","medium","high"]},
 {"id":"grok-4.6","displayName":"Grok 4.6","costTier":4,"effortLevels":["low","medium","high"]},
 {"id":"grok-4.6-fast","displayName":"Grok 4.6 Fast","costTier":8,"effortLevels":["low","medium","high","max"]},
 {"id":"gemini-3.8-flash","displayName":"Gemini 3.8 Flash","costTier":1,"effortLevels":["low","medium"]},
 {"id":"gemini-3.8-pro","displayName":"Gemini 3.8 Pro","costTier":3,"effortLevels":["low","medium","high"]},
 {"id":"kimi-k3","displayName":"Kimi K3","costTier":3,"effortLevels":["low","medium","high"]},
 {"id":"glm-5.3-flash","displayName":"GLM 5.3 Flash","costTier":1,"effortLevels":["low","medium"]},
 {"id":"deepseek-v4.1-flash","displayName":"DeepSeek V4.1 Flash","costTier":1,"effortLevels":["low","medium"]},
 {"id":"prism-cg","displayName":"Prism (Claude + GPT)","costTier":9,"effortLevels":["low","medium","high","max"]},
 {"id":"prism-g","displayName":"Prism (GPT)","costTier":9,"effortLevels":["low","medium","high","max"]},
 {"id":"prism-economy","displayName":"Prism (Economy)","costTier":0,"effortLevels":["low","medium"]},
 {"id":"o4-reasoning","displayName":"OpenAI o4 Reasoning","costTier":2,"effortLevels":["low","medium","high"]}
],"defaultModel":"claude-sonnet-5"}
JSON
  # same list with GPT-6 Astra removed, for the fallback assertion
  jq '.models |= map(select(.id != "gpt-6-astra"))' "$tmp/full.json" > "$tmp/noastra.json"
  # an allowlist with nothing but anthropic models
  cat > "$tmp/allclaude.json" <<'JSON'
{"models":[
 {"id":"claude-opus-5","displayName":"Claude Opus 5","costTier":6,"effortLevels":["low","medium","high","max"]},
 {"id":"claude-sonnet-5","displayName":"Claude Sonnet 5","costTier":4,"effortLevels":["low","medium","high"]},
 {"id":"claude-haiku-45","displayName":"Claude Haiku 4.5","costTier":2,"effortLevels":["low","medium"]}
],"defaultModel":"claude-sonnet-5"}
JSON
  # one Google pair only: if `mini` were unbounded this resolves to nothing
  cat > "$tmp/gemini.json" <<'JSON'
{"models":[
 {"id":"gemini-3.8-pro","displayName":"Gemini 3.8 Pro","costTier":3,"effortLevels":["low","medium","high"]},
 {"id":"gemini-3.8-flash","displayName":"Gemini 3.8 Flash","costTier":1,"effortLevels":["low","medium"]}
]}
JSON
  # an o-series model with no high effort, so it lands in the exclusion listing
  # where its FAMILY is printed - the only place classification is observable
  cat > "$tmp/oseries.json" <<'JSON'
{"models":[
 {"id":"claude-opus-5","displayName":"Claude Opus 5","costTier":6,"effortLevels":["low","medium","high","max"]},
 {"id":"o4-reasoning","displayName":"OpenAI o4 Reasoning","costTier":2,"effortLevels":["low","medium"]}
]}
JSON
  # an entry missing costTier entirely, and one missing effortLevels. The second
  # is the dangerous one: a null cost tier is caught a second time by rank_of,
  # but a null effort list would read as "no high effort" and silently shrink
  # the candidate set instead of failing.
  jq 'del(.models[1].costTier)' "$tmp/full.json" > "$tmp/nocost.json"
  jq 'del(.models[1].effortLevels)' "$tmp/full.json" > "$tmp/noeffort.json"

  echo "scripts/resolve-tier.sh --selftest"
  echo

  # FIRST, and before believing any verdict below: prove the STUB answered.
  # A green selftest that reached the real vendor is worse than a red one - the
  # fixture and a live allowlist can agree by accident, and then none of this
  # tested anything.
  rm -f "$tmp/stub-ran"
  run full REVIEWER
  [ -f "$tmp/stub-ran" ] && ok "discovery reached the stub, not an installed auggie" \
    || no "discovery did NOT reach the stub - an installed auggie won the PATH race and every assertion below is meaningless"
  is "REVIEWER resolves to the preferred non-anthropic model" "gpt-6-astra" "$OUT"
  is "  ...with exit 0" "0" "$RC"
  has "  ...and says so on stderr" "source=discovered" "$ERR"
  has "  ...naming the preference that won" "preference=astra" "$ERR"

  run noastra REVIEWER
  is "REVIEWER falls back to the second preference when the first is gone" "gpt-5.6-sol" "$OUT"

  run full TIER_FRONTIER_DO
  is "FRONTIER_DO takes the highest cost tier, anthropic allowed (fork 9)" "claude-opus-5" "$OUT"
  run full TIER_FRONTIER_THINK
  is "FRONTIER_THINK likewise" "claude-opus-5" "$OUT"

  run full TIER_MID
  is "MID takes the highest cost tier strictly below FRONTIER's" "gpt-6-astra" "$OUT"
  has "  ...and says which anchor it used" "below FRONTIER's" "$ERR"

  run full TIER_SMALL
  is "SMALL may be a speed tier, and takes the lowest cost tier" "gemini-3.8-flash" "$OUT"

  # Four models share cost tier 4 here. The tiebreak is the vendor's own list
  # order, and it has to be deterministic or a re-run silently rebinds a tier.
  run noastra TIER_MID
  is "a cost-tier tie breaks to the first model in the vendor's list order" "gpt-5.6-sol" "$OUT"

  # The router and speed-tier predicates, asserted as an exhaustive verdict over
  # every entry in the fixture rather than on the one winner.
  local role bad
  for role in TIER_FRONTIER_THINK TIER_FRONTIER_DO TIER_MID REVIEWER; do
    run full "$role"
    case "$OUT" in
      prism-*) no "$role must never resolve to a router blend (got $OUT)" ;;
      *flash*|*fast*|*mini*|*nano*|*lite*) no "$role must never resolve to a speed tier (got $OUT)" ;;
      *) ok "$role resolved to neither a router blend nor a speed tier ($OUT)" ;;
    esac
  done
  # Prism (Economy) is the cheapest entry in the fixture, so this is the one
  # assertion where dropping the router predicate changes what SMALL binds.
  run full TIER_SMALL
  case "$OUT" in prism-*) no "TIER_SMALL must never resolve to a router blend (got $OUT)" ;; *) ok "TIER_SMALL excludes router blends too" ;; esac

  run gemini REVIEWER
  is "a non-Flash Google model survives the speed-tier predicate ('mini' is bounded)" "gemini-3.8-pro" "$OUT"
  run gemini TIER_SMALL
  is "  ...and the Flash one is still what SMALL picks" "gemini-3.8-flash" "$OUT"

  run allclaude REVIEWER
  is "an all-anthropic allowlist gives REVIEWER exit 3" "3" "$RC"
  is "  ...and prints no id on stdout" "" "$OUT"
  has "  ...naming the predicate per model" "same family as the author" "$ERR"
  has "  ...for every model seen" "claude-haiku-45" "$ERR"
  has "  ...and refusing the account default out loud" "account default model is never read" "$ERR"
  run allclaude TIER_FRONTIER_DO
  is "  ...while the work tiers still bind (FRONTIER_DO)" "claude-opus-5" "$OUT"
  run allclaude TIER_MID
  is "  ...(MID)" "claude-sonnet-5" "$OUT"
  run allclaude TIER_SMALL
  is "  ...(SMALL)" "claude-haiku-45" "$OUT"

  run oseries REVIEWER
  is "an o-series id with no high effort leaves REVIEWER empty" "3" "$RC"
  has "  ...and is classified openai, not unknown" 'o4-reasoning [openai]' "$ERR"
  has "  ...excluded by effort, not by family" "include neither high nor max" "$ERR"

  run nocost TIER_FRONTIER_DO
  is "an entry missing costTier exits 4" "4" "$RC"
  has "  ...from the required-fields guard, not a later one" "is missing one of id/displayName/costTier/effortLevels" "$ERR"
  has "  ...pointing at the schema knobs" "runbook step 5a" "$ERR"
  has "  ...and printing the raw entry to read the real keys off" '"displayName": "GPT-6 Astra"' "$ERR"
  run noeffort TIER_FRONTIER_DO
  is "an entry missing effortLevels exits 4 rather than shrinking the set" "4" "$RC"
  has "  ...from the required-fields guard" "is missing one of id/displayName/costTier/effortLevels" "$ERR"

  # bash keeps a var assigned in front of a FUNCTION call set after the call
  # returns, so this one is unset explicitly rather than trusted to scope out.
  REVIEWER_MODEL="a-pinned-id" run full REVIEWER
  is "an explicit REVIEWER_MODEL is returned untouched" "a-pinned-id" "$OUT"
  has "  ...as source=pinned" "source=pinned" "$ERR"
  unset REVIEWER_MODEL

  # --write-conf, and the round-trip. bin/harness is NOT invoked: `harness add
  # --tool auggie` writes a pointer file and has no --dry-run, and
  # config/models.auggie.conf is a different branch's deliverable. What matters
  # is that load_models could parse this file, so the parser's own two-line
  # normalisation is replicated here and run against the generated bytes.
  run full --write-conf
  is "--write-conf exits 0" "0" "$RC"
  local k v got=""
  while IFS='=' read -r k v; do
    k="${k%%#*}"; k="$(printf '%s' "$k" | tr -d '[:space:]')"
    [ -n "$k" ] || continue
    v="${v%%#*}"; v="$(printf '%s' "$v" | tr -d '[:space:]')"
    got="$got$k=$v;"
  done < "$tmp/models.auggie.conf"
  is "--write-conf round-trips through load_models' KEY=value normalisation" \
     "TIER_FRONTIER_THINK=claude-opus-5;TIER_FRONTIER_DO=claude-opus-5;TIER_MID=gpt-6-astra;TIER_SMALL=gemini-3.8-flash;" \
     "$got"
  run full --write-conf
  is "--write-conf refuses to overwrite an existing conf" "2" "$RC"
  has "  ...saying --force is the way past it" "--force" "$ERR"
  run noastra --write-conf --force
  is "--write-conf --force re-discovers" "0" "$RC"
  run full TIER_MID
  is "an existing conf is a pin: discovery never overrides it" "gpt-6-astra" "$OUT"
  has "  ...reported as source=conf" "source=conf" "$ERR"
  rm -f "$tmp/models.auggie.conf"

  echo
  if [ "$F" -gt 0 ]; then printf 'FAILED %d of %d assertions\n' "$F" "$T"; exit 1; fi
  printf 'OK all %d assertions passed\n' "$T"
}

# ---------------------------------------------------------------- arg handling
ROLE=""; WRITE=0; FORCE=0
[ $# -gt 0 ] || die "usage: resolve-tier.sh <TIER_FRONTIER_THINK|TIER_FRONTIER_DO|TIER_MID|TIER_SMALL|REVIEWER> [--write-conf [--force]] | --selftest"
while [ $# -gt 0 ]; do
  case "$1" in
    --selftest)   selftest; exit $? ;;
    --write-conf) WRITE=1 ;;
    --force)      FORCE=1 ;;
    -h|--help)    sed -n '5,30p' "$SELF"; exit 0 ;;
    TIER_FRONTIER_THINK|TIER_FRONTIER_DO|TIER_MID|TIER_SMALL|REVIEWER) ROLE="$1" ;;
    *) die "unknown argument: $1" ;;
  esac
  shift
done
[ "$FORCE" = "0" ] || [ "$WRITE" = "1" ] || die "--force only means something with --write-conf"
need_jq() { command -v jq >/dev/null 2>&1 || die "required tool not found: jq"; }
need_jq

if [ "$WRITE" = "1" ]; then
  write_conf "$FORCE"
  [ -n "$ROLE" ] || exit 0
fi
[ -n "$ROLE" ] || die "no role given"
resolve "$ROLE"
report "$ROLE"
printf '%s\n' "$SEL_ID"
